DROP FUNCTION IF EXISTS EIKI.GET_PREF_RATIO;

DELIMITER $$
CREATE FUNCTION GET_PREF_RATIO(PREF_IN INTEGER, PREF_TOTAL INTEGER)
    RETURNS FLOAT
    NOT DETERMINISTIC
BEGIN
    DECLARE RETURN_VAL FLOAT;
    IF PREF_TOTAL = 0 THEN
        SET RETURN_VAL = 0.0;
    ELSE
        SET RETURN_VAL = TRUNCATE(((PREF_IN / PREF_TOTAL) * 100.0), 1);
    END IF;
    RETURN (RETURN_VAL);
END$$
DELIMITER ;

